<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>esp32_wasd_host</name> <!-- Your package name -->
  <version>0.0.0</version>
  <description>Keyboard WASD node sending integer commands for ESP32 micro-ROS</description>
  <maintainer email="your_email@example.com">Your Name</maintainer> <!-- <<< UPDATE THIS -->
  <license>Apache License 2.0</license> <!-- Or your preferred license -->

  <!-- Dependencies needed to run the code -->
  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>

  <!-- Dependencies for testing (good practice) -->
  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>